In [1]:
# imported all the requird libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# read the dataset by using pandas

data=pd.read_csv(r'C:\Users\Sonu\Desktop\data\Adult.csv',header=None)
data

0                  1       2            3   4                    5   \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9      10  11  12  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   13      14  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3       United-States   <=50K  
4                Cuba   <=50K  
...               ...     ...  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K  

[32561 rows x 15 columns]

In [3]:
# assigining column name in dataset

data.columns = ["age","workclass","fnlwgt","education","education_num","marital_status","occupation","realtionship","race","sex",
                "capital_gain","capital_loss","hours_per_week","native_country","income"]
data

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    realtionship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [4]:
# by using pandas function checking size of dataset

data.shape

(32561, 15)

In [5]:
data.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [6]:
# # by using pandas function checking null value present or not in dataset

data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
realtionship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [7]:
# droping unusefull data from the datset

data1=data.drop(['education','fnlwgt'],axis=1)
data1.shape

(32561, 13)

In [8]:
# checking unique values from the dataset

for i in data1.columns:
    print({i:data1[i].unique()})

{'age': array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43,
       54, 35, 59, 56, 19, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47,
       46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58,
       26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82,
       83, 84, 85, 86, 87], dtype=int64)}
{'workclass': array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)}
{'education_num': array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8],
      dtype=int64)}
{'marital_status': array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)}
{'occupation': array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-m

In [9]:
# replacing the '?' to nan values in the dataset

data1=data1.replace(' ?',np.nan)
data1

age          workclass  education_num       marital_status  \
0       39          State-gov             13        Never-married   
1       50   Self-emp-not-inc             13   Married-civ-spouse   
2       38            Private              9             Divorced   
3       53            Private              7   Married-civ-spouse   
4       28            Private             13   Married-civ-spouse   
...    ...                ...            ...                  ...   
32556   27            Private             12   Married-civ-spouse   
32557   40            Private              9   Married-civ-spouse   
32558   58            Private              9              Widowed   
32559   22            Private              9        Never-married   
32560   52       Self-emp-inc              9   Married-civ-spouse   

               occupation    realtionship    race      sex  capital_gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband   White     Male             0   
2       Handlers-cleaners   Not-in-family   White     Male             0   
3       Handlers-cleaners         Husband   Black     Male             0   
4          Prof-specialty            Wife   Black   Female             0   
...                   ...             ...     ...      ...           ...   
32556        Tech-support            Wife   White   Female             0   
32557   Machine-op-inspct         Husband   White     Male             0   
32558        Adm-clerical       Unmarried   White   Female             0   
32559        Adm-clerical       Own-child   White     Male             0   
32560     Exec-managerial            Wife   White   Female         15024   

       capital_loss  hours_per_week  native_country  income  
0                 0              40   United-States   <=50K  
1                 0              13   United-States   <=50K  
2                 0              40   United-States   <=50K  
3                 0              40   United-States   <=50K  
4                 0              40            Cuba   <=50K  
...             ...             ...             ...     ...  
32556             0              38   United-States   <=50K  
32557             0              40   United-States    >50K  
32558             0              40   United-States   <=50K  
32559             0              20   United-States   <=50K  
32560             0              40   United-States    >50K  

[32561 rows x 13 columns]

In [10]:
# after relacing checking null values

data1.isnull().sum()

age                  0
workclass         1836
education_num        0
marital_status       0
occupation        1843
realtionship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [11]:
# filling  the null values by using mode value 

for i in ['workclass','occupation','native_country']:
    data1[i].fillna(data1[i].mode()[0],inplace=True)

In [12]:
# again checking null value 

data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
realtionship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [13]:
# creating object datatype from the dataset

colname=[]
for i in data1:
    if data1[i].dtype=='object':
        colname.append(i)
colname

['workclass',
 'marital_status',
 'occupation',
 'realtionship',
 'race',
 'sex',
 'native_country',
 'income']

In [14]:
# converting object data into numerical data

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for i in colname:
    data1[i]=le.fit_transform(data1[i])       # sklearn function 
    
data1

# income (0----> less the 50k , 1----> greater then 50k) on data remeber

age  workclass  education_num  marital_status  occupation  \
0       39          6             13               4           0   
1       50          5             13               2           3   
2       38          3              9               0           5   
3       53          3              7               2           5   
4       28          3             13               2           9   
...    ...        ...            ...             ...         ...   
32556   27          3             12               2          12   
32557   40          3              9               2           6   
32558   58          3              9               6           0   
32559   22          3              9               4           0   
32560   52          4              9               2           3   

       realtionship  race  sex  capital_gain  capital_loss  hours_per_week  \
0                 1     4    1          2174             0              40   
1                 0     4    1             0             0              13   
2                 1     4    1             0             0              40   
3                 0     2    1             0             0              40   
4                 5     2    0             0             0              40   
...             ...   ...  ...           ...           ...             ...   
32556             5     4    0             0             0              38   
32557             0     4    1             0             0              40   
32558             4     4    0             0             0              40   
32559             3     4    1             0             0              20   
32560             5     4    0         15024             0              40   

       native_country  income  
0                  38       0  
1                  38       0  
2                  38       0  
3                  38       0  
4                   4       0  
...               ...     ...  
32556              38       0  
32557              38       1  
32558              38       0  
32559              38       0  
32560              38       1  

[32561 rows x 13 columns]

In [22]:
x=data1.values[:,0:-1]
y=data1.values[:,-1]

In [31]:
x=data1.iloc[:,0:-1]
x

age  workclass  education_num  marital_status  occupation  \
0       39          6             13               4           0   
1       50          5             13               2           3   
2       38          3              9               0           5   
3       53          3              7               2           5   
4       28          3             13               2           9   
...    ...        ...            ...             ...         ...   
32556   27          3             12               2          12   
32557   40          3              9               2           6   
32558   58          3              9               6           0   
32559   22          3              9               4           0   
32560   52          4              9               2           3   

       realtionship  race  sex  capital_gain  capital_loss  hours_per_week  \
0                 1     4    1          2174             0              40   
1                 0     4    1             0             0              13   
2                 1     4    1             0             0              40   
3                 0     2    1             0             0              40   
4                 5     2    0             0             0              40   
...             ...   ...  ...           ...           ...             ...   
32556             5     4    0             0             0              38   
32557             0     4    1             0             0              40   
32558             4     4    0             0             0              40   
32559             3     4    1             0             0              20   
32560             5     4    0         15024             0              40   

       native_country  
0                  38  
1                  38  
2                  38  
3                  38  
4                   4  
...               ...  
32556              38  
32557              38  
32558              38  
32559              38  
32560              38  

[32561 rows x 12 columns]

In [35]:
y=data1.iloc[:,-1]
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: income, Length: 32561, dtype: int32

In [16]:
y

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [17]:
x

array([[39,  6, 13, ...,  0, 40, 38],
       [50,  5, 13, ...,  0, 13, 38],
       [38,  3,  9, ...,  0, 40, 38],
       ...,
       [58,  3,  9, ...,  0, 40, 38],
       [22,  3,  9, ...,  0, 20, 38],
       [52,  4,  9, ...,  0, 40, 38]], dtype=int64)

In [18]:

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)


In [19]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(22792, 12)
(9769, 12)
(22792,)
(9769,)


In [20]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)
print(list(zip(y_test,y_pred)))

[0 0 1 ... 0 0 1]
[(0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 1), (1, 0), (0, 1), (1, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (1, 1), (0, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 1), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (1, 0), (1, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification_report:')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of thr model :',acc)

[[7044  379]
 [1473  873]]
classification_report:
              precision    recall  f1-score   support

           0       0.83      0.95      0.88      7423
           1       0.70      0.37      0.49      2346

    accuracy                           0.81      9769
   macro avg       0.76      0.66      0.68      9769
weighted avg       0.80      0.81      0.79      9769

accuracy of thr model : 0.8104207185996519
